Chart0_0:
  ChartType: ScalarFlds
  OutlineText: true
  UseDivCmap: false
  cmap: None
  cnorm_type: Linear
  cpow_num: 0.6
  flds_type: B_total
  div_midpoint: 0.0
  face_color: gainsboro
  interpolation: none
  normalize_density: true
  set_color_limits: false
  set_v_max: false
  set_v_min: false
  show_cbar: true
  show_cpu_domains: false
  show_labels: true
  show_shock: false
  spatial_x: true
  spatial_y: 0
  stretch_colors: false
  twoD: 1
  v_max: 10
  v_min: 0
MainParamDict:
  2DSlicePlane: 0
  Average1D: 0
  AxLabelSize: 11
  ClearFig: true
  ColorMap: Blue/Green/Red/Yellow
  ConstantShockVel: true
  DivColorMap: Blue/Green/Red/Yellow
  DoLorentzBoost: false
  FFTLeft: 0.0
  FFTRelative: true
  FFTRight: 200.0
  FFT_color: k
  FigSize:
  - 12.0
  - 6.22
  GammaBoost: 0.0
  HAxesExtent:
  - 18
  - 92
  - 0
  - -1
  HCbarExtent:
  - 0
  - 4
  - 0
  - -1
  HSubPlotParams:
    bottom: 0.06
    hspace: 0.3
    left: 0.06
    right: 0.95
    top: 0.91
    wspace: 0.15
  HorizontalCbars: false
  ImageAspect: 0
  LinkK: true
  LinkSpatial: 2
  LoopPlayback: true
  MaxCols: 8
  MaxRows: 8
  NumFontSize: 11
  NumOfCols: 1
  NumOfRows: 1
  PrtlStride: 5
  Recording: false
  Reload2End: true
  SetkLim: false
  SetxLim: false
  SetyLim: false
  ShowTitle: true
  SkipSize: 5
  VAxesExtent:
  - 4
  - 90
  - 0
  - 92
  VCbarExtent:
  - 4
  - 90
  - 94
  - 97
  VSubPlotParams:
    bottom: 0.06
    hspace: 0.15
    left: 0.06
    right: 0.95
    top: 0.93
    wspace: 0.23
  WaitTime: 0.01
  WindowSize: 1200x700
  annotateTextSize: 18
  cbarLabelPad: 15
  dpi: 100
  electron_color: '#fca636'
  electron_fit_color: yellow
  ion_color: '#d6556d'
  ion_fit_color: r
  kLeft: 0.1
  kRight: 1.0
  legendLabelSize: 11
  shock_color: w
  xLabelPad: 0
  xLeft: 0.0
  xLimsRelative: false
  xRight: 100.0
  yBottom: 0.0
  yLabelPad: 0
  ySlice: 0.5
  yTop: 100.0
  zSlice: 0.0
general:
  ConfigName: Default
